import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link
        href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap"
        rel="stylesheet"
      />
      <body className={`font-montserrat flex flex-col min-h-screen`}>
        <Header />
        <div className="items-center">{children}</div>
        <div className="mt-auto ">
          <Footer />
        </div>
      </body>
    </html>
  );
}
